# 命令配置列表
commands:
  - name: run_telegra_selenium
    module: backendServices.src.socialPlatforms.telegraGO.telegraSelenium
    class: telegraSelenium
    method: main
    params:
      - pcname
      - queue_url
      - genre
      - platform
      - stacking_min
      - stacking_max
      - title_alt
      - alt_text
      - sort
      - isarts
      - postingStyle
      - group
      - start
      - end


  - name: run_blogger_selenium
    module: backendServices.src.socialPlatforms.bloggerGO.bloggerSelenium
    class: bloggerSelenium
    method: main
    params:
      - pcname
      - queue_url
      - genre
      - platform
      - stacking_min
      - stacking_max
      - title_alt
      - alt_text
      - sort
      - isarts
      - postingStyle
      - group
      - start
      - end

  - name: note_post_text
    module: backendServices.src.socialPlatforms.nodeGO.notePostText
    class: notePostText
    method: main
    params:
      - pcname
      - queue_url
      - genre
      - platform
      - stacking_min
      - stacking_max
      - title_alt
      - alt_text
      - sort
      - isarts
      - postingStyle
      - group
      - start
      - end

  - name: getCookie
    module: backendServices.src.socialPlatforms.nodeGO.getCookie
    class: getCookie
    method: run
    params:
      - pcname
      - queue_url
      - adsIDlist

  - name: generate_article
    module: backendServices.src.generateArticle.generate_article
    class: generateArticle
    method: run
    params:
      - pcname
      - queue_url
      - isopenAI
      - type
      - max_length
      - promptID
      - sortID
      - user
      - theme
      - Keywords
      - ATag
      - link
      - language


# 可以继续添加更多命令
# 每个命令都应包含以下字段:
# name: 命令的唯一标识符
# module: 包含要执行的代码的Python模块路径
# class: (可选) 如果要执行的是类方法,这里指定类名
# method 或 function: 要执行的方法或函数名
# params: 执行方法或函数所需的参数列表
