# 命令配置列表
commands:
  - name: run_post_spliceGo
    module: backendServices.src.assistance.postSpliceGo
    class: postSpliceGo
    method: main
    params:
      - pcname
      - queue_url
      - genre
      - platform
      - stacking_min
      - stacking_max
      - title_alt
      - alt_text
      - sort
      - isarts
      - postingStyle
      - group
      - start
      - end

  - name: getCookie
    module: backendServices.src.socialPlatforms.noteGO.getCookie
    class: getCookie
    method: run
    params:
      - pcname
      - queue_url
      - adsIDlist

  - name: generate_article
    module: backendServices.src.articleSome.add_article
    class: generateArticle
    method: run
    params:
      - pcname
      - queue_url
      - max_length
      - source
      - type
      - promptID
      - sortID
      - theme
      - Keywords
      - ATag
      - link
      - language
      - user

  - name: postSqlArticle
    module: backendServices.src.articleSome.post_sql_article
    class: postSqlArticle
    method: main
    params:
      - pcname
      - queue_url
      - platform
      - group
      - post_max
      - sortID
      - type
      - commission
      - isAI
      - user
      - language
      - isSecondary



# 可以继续添加更多命令
# 每个命令都应包含以下字段:
# name: 命令的唯一标识符
# module: 包含要执行的代码的Python模块路径
# class: (可选) 如果要执行的是类方法,这里指定类名
# method 或 function: 要执行的方法或函数名
# params: 执行方法或函数所需的参数列表
