# 命令配置列表
commands:
  - name: run_telegra_selenium
    module: backendServices.src.socialPlatforms.telegraGO.telegraSelenium
    class: telegraSelenium
    method: main
    params:
      - genre
      - platform
      - stacking_min
      - stacking_max
      - alt_text
      - group
      - start
      - end
  - name: run_blogger_selenium
    module: backendServices.src.socialPlatforms.bloggerGO.bloggerSelenium
    class: bloggerSelenium
    method: main
    params:
      - genre
      - platform
      - stacking_min
      - stacking_max
      - alt_text
      - group
      - start
      - end

  - name: test1  # 另一个命令的名称
    module: backendServices.examples.test1  # 模块路径
    class: test  # 类名
    method: run  # 方法名
    params: []  # 无参数

# 可以继续添加更多命令
# 每个命令都应包含以下字段:
# name: 命令的唯一标识符
# module: 包含要执行的代码的Python模块路径
# class: (可选) 如果要执行的是类方法,这里指定类名
# method 或 function: 要执行的方法或函数名
# params: 执行方法或函数所需的参数列表
